name: Daily Telegram Book Post

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9:00 UTC (adjust as needed)

jobs:
  post-books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Save credentials.json from secret
        run: |
          echo "${{ secrets.GOOGLE_CREDS_BASE64 }}" | base64 --decode > credentials.json

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          python bot.py
