name: Daily Telegram Book Post

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 8:00 AM UTC
  workflow_dispatch:      # Enables manual trigger

jobs:
  post_to_telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client requests

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          python bot.py
